### ISSUE TITLE
Simplify extract_cal

### ISSUE THREAD

**Issue by jrenfree** [kstierhoff/atm#1]
Could it be possible to simplify extract_cal so that the only required input is the calibration file to be read? That is, is there really a need for the user to specify the vessel and survey name? Seems like that could be added by the user after-the-fact.

**Comment by kstierhoff** [comment]
Updated `extract_cal` and `extract_cal_fm` to be more generic by setting `vessel.name`, `survey.name`, and `cal.group` to NA_character_.
